apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app 
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app 
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
      - name: my-app 
        image: my-app:v1.0
        ports:
        - name: "http"
          containerPort: 8080
        - name: "metrics"
          containerPort: 2112
        env:
        - name: "DATABASE_URL"
          value: "postgres://user:password@host/db"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: "my-app-data"
          mountPath: /data
      volumes:
      - name: "my-app-data"
        persistentVolumeClaim:
          claimName: "my-app-data"

---