name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy

      - name: Build kptn
        run: make build

      - name: Run tests
        run: make test

      - name: Run go fmt
        run: go fmt ./...

      - name: Verify go fmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files need to be formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Verify build
        run: ./kptn version
